"""add inventory uniqueness constraint

Revision ID: ef3b025a09b8
Revises: 97ef2d79bf2e
Create Date: 2026-08-08 13:27:51.433579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef3b025a09b8'
down_revision: Union[str, Sequence[str], None] = '97ef2d79bf2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_inventory_store_product', 'inventory', ['store_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_inventory_store_product', 'inventory', type_='unique')
    # ### end Alembic commands ###
